config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'groups/index'
  get 'groups/show'
  get 'groups/edit'
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  get "book_comments"=>"books#show"
  
  end
  
  get "search" => "searches#search"
  
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => 'relationships#followings', as: 'followings'
    get "followers" => 'relationships#followers', as: 'followers'
    get "search" => "users#search"
  end
  
  resources :messages,only: [:create]
  resources :rooms, only: [:create, :show]
  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    resource :user_groups, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  resources :user_groups, only: [:index]
  
  resources :notifications, only: [:index, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  

end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user 
  belongs_to :group
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @user = current_user
    @book = Book.new
    @groups = @user.groups
  end
    

  def create
    user_group = current_user.user_groups.new(group_id: params[:group_id])
    user_group.save
    redirect_to request.referer
  end
  
  def destroy
    user_group = current_user.user_groups.find_by(group_id: params[:group_id])
    user_group.destroy
    redirect_to request.referer
  end
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/user_groups/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'layouts/errors', obj: @book %>
      <%= render 'books/form', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Groups</h2>
      <div><%=link_to "グループを作成する",new_group_path %> |　<%=link_to "グループ一覧",groups_path %></div>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>GroupName</th>
            <th>introduction</th>
            <th colspan='3'></th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
            <tr>
              <td><%= image_tag group.get_group_image(50, 50) %></td>
              <td><%= link_to group.name, group_path(group) %></td>
              <td><%= group.introduction %></td>
              <td><%= group.users.count %>人参加中</td>
              <td>
                <% if group.owner_id ==  current_user.id %>
                  <%= link_to 'Edit', edit_group_path(group), class: "btn btn-sm btn-success" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>