config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'groups/index'
  get 'groups/show'
  get 'groups/edit'
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  get "book_comments"=>"books#show"
  
  end
  
  get "search" => "searches#search"
  
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => 'relationships#followings', as: 'followings'
    get "followers" => 'relationships#followers', as: 'followers'
    get "search" => "users#search"
  end
  
  resources :messages,only: [:create]
  resources :rooms, only: [:create, :show]
  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    resource :user_groups, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  resources :user_groups, only: [:index]
  
  resources :notifications, only: [:index, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  

end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
    belongs_to :book, optional: true
    belongs_to :room, optional: true
    belongs_to :visiter, class_name: 'User', foreign_key: 'visiter_id', optional: true
    belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
  
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end
  
  def destroy
    notification = Notification.find(params[:id]).destroy

  end
  
  def destroy_all
    current_user.passive_notifications.destroy_all
    redirect_to notifications_path
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
  
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.erb
<ul>
  <% notifications.each do |notification| %>
  <li>
    <%= image_tag notification.visiter.get_profile_image(30, 30) %>
    <strong><%= link_to user_path(notification.visiter_id) do %><%= notification.visiter.name %><% end %></strong>さんから
    <% case notification.action %>
    <% when 'message' then %>
      <strong><%= link_to room_path(notification.room_id) do %>新着メッセージ<% end %></strong>があります。
    <% else %>
      <strong><%= link_to book_path(notification.book_id) do %><%= notification.book.title %><% end %></strong>にコメントがありました。
    <% end %>
      <%= "(#{time_ago_in_words(notification.created_at)} 前)" %><p class="text-right"><%= link_to notification_path(notification.id), method: :delete,class:"btn btn-light" do %>削除<i class="fas fa-trash"></i><% end %></p>
  </li>
  <% end %>
</ul>

app/views/notifications/index.html.erb
<div class="container">
  <div class="row justify-content-center mx-auto">
    <div class="notification_box">
      <h4 class="text-center"><i class="fas fa-bell"></i>新着通知</h4>
      <p class="text-right"><%= link_to destroy_all_notifications_path, method: :delete,class:"btn btn-light" do %>全削除<i class="fas fa-trash"></i><% end %></p>
      <% if @notifications.exists? %>
        <%= render 'notification', notifications: @notifications %>
      <% else %>
      <p>通知はありません</p>
      <% end %>
    </div>
  </div>
</div>