config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'groups/index'
  get 'groups/show'
  get 'groups/edit'
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  get "book_comments"=>"books#show"
  
  end
  
  get "search" => "searches#search"
  
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => 'relationships#followings', as: 'followings'
    get "followers" => 'relationships#followers', as: 'followers'
    get "search" => "users#search"
  end
  
  resources :messages,only: [:create]
  resources :rooms, only: [:create, :show]
  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    resource :user_groups, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  resources :user_groups, only: [:index]
  
  resources :notifications, only: [:index, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups, source: :user
  
  has_one_attached :group_image
  
  def get_group_image(width, heigh)
    unless group_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      group_image.attach(io: File.open(file_path), filename: 'default-image-jpg', content_type: 'image/jpeg')
    end
    group_image.variant(resize_to_limit: [width, heigh]).processed
  end
  
  def includeUser?(user)
    user_groups.exists?(user_id: user.id)
  end
  validates :name, presence: true
  validates :introduction, presence: true , length: { maximum: 500 }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @book = Book.new
    @groups = Group.all
  end

  def show
    @book = Book.new
    @group = Group.find(params[:id])
  end
  
  def new
    @group = Group.new
  end
  
  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    if @group.save
       UserGroup.create(group_id: @group.id, user_id: current_user.id)
      redirect_to group_path(@group)
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end
  
  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_path(@group)
    else
      render "edit"
    end
  end
  
  def new_mail
    @group = Group.find(params[:group_id])    
  end
  
  def send_mail
    @group = Group.find(params[:group_id])
    group_users = @group.users
    @mail_title = params[:mail_title]
    @mail_content = params[:mail_content]
    GroupEventMailer.send_mail(@mail_title, @mail_content, group_users).deliver
  end

  
  private
  
  def group_params
    params.require(:group).permit(:name, :introduction, :group_image)
  end
  
  def ensure_correct_user
    group = Group.find(params[:id])
    unless group.owner_id == current_user.id
      redirect_to groups_path
    end
  end
  
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with model: group, local:true do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :introduction　%>
    <%= f.text_area :introduction, class: "form-control" %>
  </div>  
  <div class="form-group">
    <%= f.label :image　%>
     <%= f.file_field :group_image, placeholder: "グループ画像", accept: "image/*" %>
  </div>  
  
  <div class="form-group">
    <%= f.submit class: "btn btn-info" %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Editing Group</h3>Group<%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'layouts/errors', obj: @book %>
      <%= render 'books/form', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Groups</h2>
      <div><%=link_to "グループを作成する",new_group_path %> |<%=link_to "参加済グループ",user_groups_path %></div>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th style="width: 8%"></th>
            <th style="width: 20%">GroupName</th>
            <th style="width: 30%">introduction</th>
            <th colspan='3'  style="width: 30%"></th>
          </tr>
        </thead>
        <tbody class="table_data">
          <% @groups.each do |group| %>
            <tr>
              <td><%= image_tag group.get_group_image(50, 50) %></td>
              <td><%= link_to group.name, group_path(group) %></td>
              <td><%= group.introduction %></td>
              <td><%= group.users.count %>人参加中</td>
              <td>
                <% if group.owner_id ==  current_user.id %>
                  <%= link_to 'Edit', edit_group_path(group), class: "btn btn-sm btn-success" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Create Group</h3>
      <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Event Mail</h2>
    <%= form_with url: group_send_mail_path(@group), method: :get, local: true do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :mail_title,class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label:content %>
        <%= f.text_area :mail_content,class:"form-control" %>
      </div>
      <div>
        <%= f.submit"送信", class: "btn btn-sm btn-success" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class="container d-flex flex-column align-items-center text-left">
  <div>
    <h3 class="mb-3">送信が完了しました</h3>
    <div>
      [タイトル]<p class="font-weight-bold"> <%= @mail_title %></p>
      [本文]<p class="font-weight-bold"></p> <%= safe_join(@mail_content.split("\n"),tag(:br)) %></p>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'layouts/errors', obj: @book %>
      <%= render 'books/form', book: @book %>
    </div>
    
    <div class='col-md-8 offset-md-1'>
      <h2>Group Detail</h2>
      <table class='table table-hover table-inverse table_data'>
        <tr>
          <td><%= image_tag @group.get_group_image(70, 70) %></td>
          <td><%= link_to @group.name, group_path(@group) %></td>
          <td><%= @group.introduction %></td>
          <td><%= @group.users.count %>人参加中</td>
          <td>
            <% if @group.owner_id ==  current_user.id %>
              <%= link_to 'Edit', edit_group_path(@group), class: "btn btn-sm btn-success" %>
            <% elsif @group.includeUser?(current_user) %>
              <%= link_to 'Leave this group', group_user_groups_path(@group), method: :delete, "data-confirm" => "Are you sure?", class: "btn btn-sm btn-danger" %>
            <% else %>
              <%= link_to 'Join this group',  group_user_groups_path(@group), method: :post, class: "btn btn-sm btn-success" %>
            <% end %>
          </td>
        </tr>
      </table>
      <% if @group.owner_id ==  current_user.id %>
        <%= link_to "Notice an Event",group_new_mail_path(@group), class: "btn btn-sm btn-info" %>
      <% end %>
      <h4>Members</h4>
      <table>
        <tbody>
          <% @group.users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image(40, 40) %></td>
              <td><%= link_to user.name, user_path(user), data: {"turbolinks"=>false} %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    
    
  </div>
</div>