config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'groups/index'
  get 'groups/show'
  get 'groups/edit'
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  get "book_comments"=>"books#show"
  
  end
  
  get "search" => "searches#search"
  
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => 'relationships#followings', as: 'followings'
    get "followers" => 'relationships#followers', as: 'followers'
    get "search" => "users#search"
  end
  
  resources :messages,only: [:create]
  resources :rooms, only: [:create, :show]
  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    resource :user_groups, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  resources :user_groups, only: [:index]
  
  resources :notifications, only: [:index, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :favorites, dependent: :destroy
  has_many :book_comments

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries
  has_many :access_counts, dependent: :destroy
  has_many :user_groups, dependent: :destroy
  has_many :groups, through: :user_groups, source: :group

  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visiter_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


  def get_profile_image(width, heigh)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image-jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, heigh]).processed
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end
  
  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
  
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update,:edit]
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.page(params[:page]).reverse_order
    @today_book = @books.created_today
    @yesterday_book = @books.created_days_ago(1)
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
    
    
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cue|
        @userEntry.each do |ue|
          if cue.room_id == ue.room_id then
            @isRoom = true
            @chatroom = cue.room_id
          else
            @room = Room.new
            @entry = Entry.new
          end            
        end
      end
    end
  end
    
    
  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end
  
  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
      @create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{@create_at}%"])
      @search_book_count = @search_book.count
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
  
  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user) , notice: 'ゲストユーザーはプロフィール画面へ遷移できません。'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(50, 50) %></td>
        <td><%= user.name %></td>
        
        <% if user != current_user %>
          <td>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー中", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォロー", user_relationships_path(user.id), method: :post %>
            <% end %>
          </td>
        <% else %>
          <td></td>
        <% end %>    

        <td><%= link_to 'Show', user, data: {"turbolinks"=>false} %></td>
        <td></td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image(100, 100) %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th><%= link_to "followers", user_followers_path(user) %></th>
    <th><%= user.followers.count %>人</th>
  </tr>
  <tr>
    <th><%= link_to "follows", user_followings_path(user) %></th>
    <th><%= user.followings.count %>人</th>
  </tr>
  <% if user != current_user %>
  <tr>
      <% if current_user.following?(user) %>
        <th><%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info btn-sm btn-block" %></th>

      <% else %>
        <th><%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %></th>
        <th></th>
      <% end %>
      <% if (current_user.following?(user)) && (user.following?(current_user)) %>
        <% if isRoom == true %>
          <th><%=link_to "DMをする", room_path(room), class: "btn btn-info btn-sm btn-block" %></th>
        <% else %>
          <th>
            <%= form_with model: room, url: rooms_path, method: :post do |f| %>
              <%= f.fields_for :entry do |e| %>
                <%= e.hidden_field :user_id, value: user.id %>
              <% end %>
              <%= f.submit "DMを始める",  class: "btn btn-info btn-sm btn-block"%>
            <% end %>
          </th>
        <% end %>
      <% end %>  
      
  </tr>
  
  <% end %>
  
</table>
<% if user.name != "guestuser" %>
  <div class='row'>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
<% end %>

app/views/users/_search.html.erb
<% if search_book == "日付を選択してください" %>
  日付を選択してください
<% else %>  

  <div><%= create_at %> の投稿件数： <%= search_book_count %></div>
  <ul>
    <% search_book.each do |book| %>
      <li><%= link_to book.title, book_path(book) %></li>
    <% end %>
  </ul>
  
<% end %>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
        <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
        <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
        <div><%=link_to "グループを作成する",new_group_path %> | <%=link_to "グループ一覧",groups_path %></div> 
        <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$("#search_result").html("<%= j(render 'search', search_book_count: @search_book_count, create_at: @create_at, search_book: @search_book) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user, isRoom: @isRoom, room: @chatroom %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      <div class="submenu">
        <h5>■投稿数の前日比・前週比</h4>
          <div class="hidden">
          <table class="table">
            <thead>
              <tr>
                <th>今日の投稿</th>
                <th>昨日の投稿</th>
                <th>前日比</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= @today_book.count %></td>
                <td><%= @yesterday_book.count %></td>
                <td>
                  <% if @yesterday_book.count == 0 %>
                    前日の投稿はありません
                  <% else %>
                    <% @the_day_before = @today_book.count / @yesterday_book.count.to_f %> 
                    <%= (@the_day_before * 100).round %>%
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>
          <table class="table">
            <thead>
              <tr>
                <th>今週の投稿</th>
                <th>先週の投稿</th>
                <th>比</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= @this_week_book.count %></td>
                <td><%= @last_week_book.count %></td>
                <td>
                  <% if @last_week_book.count == 0 %>
                    先週の投稿はありません
                  <% else %>
                    <% @the_week_before = @this_week_book.count / @last_week_book.count.to_f %> 
                    <%= (@the_week_before * 100).round %>%
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>
          </div>
      </div>
      <div class="submenu">
        <h5>■7日間分の投稿数</h4>
        <div class="hidden">
          <table class="table text-center">
            <thead>
              <tr>
                <th>6日前</th>
                <th>5日前</th>
                <th>4日前</th>
                <th>3日前</th>
                <th>2日前</th>
                <th>昨日</th>
                <th>今日</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= @books.created_days_ago(6).count %></td>
                <td><%= @books.created_days_ago(5).count %></td>
                <td><%= @books.created_days_ago(4).count %></td>
                <td><%= @books.created_days_ago(3).count %></td>
                <td><%= @books.created_days_ago(2).count %></td>
                <td><%= @books.created_days_ago(1).count %></td>
                <td><%= @today_book.count %></td>
              </tr>
            </tbody>
          </table>
          <canvas id="myLineChart"></canvas>
        </div>
      </div>
      <div class="submenu">
        <h5>■投稿検索</h4>
        <div class="hidden">
          <%= form_with url: user_search_path(@user), method: :get, local:false do |f| %>
            <%= f.date_field :created_at %>
            <%= f.submit '検索' %>
          <% end %>
          
          <div id="search_result">
            <% if @search_book.present? %>
              <%= render 'search', search_book:@search_book %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
　  $(document).ready(function(){
    $('.submenu h5').on('click', function(){
      $(this).next().toggleClass('hidden');
    });
  });
  
</script>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  
  <script>
    $(document).ready(function(){
      var ctx = document.getElementById("myLineChart");
      var myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '昨日', '今日'],
          datasets: [
            {
              label: '投稿数',
              data: [
                <%= @books.created_days_ago(6).count %>,
                <%= @books.created_days_ago(5).count %>,
                <%= @books.created_days_ago(4).count %>,
                <%= @books.created_days_ago(3).count %>,
                <%= @books.created_days_ago(2).count %>,
                <%= @books.created_days_ago(1).count %>,
                <%= @today_book.count %>
              ],
              borderColor: "rgba(0,0,255,1)",
              backgroundColor: "rgba(0,0,0,0)",
              tension: 0.4
            }
          ],
        },
        options: {
          title: {
            display: true,
            text: '7日間の投稿数の比較'
          },
          responsive: true,
          scales: {
            y:{
              suggestedMin: 0,
              suggestedMax: 10
            },
            x:{
              stacked: true
            },
          },
        }
      });
    });
  </script>